sudo: false
compiler: clang
language: node_js

node_js:
  - "8"

branches:
  only:
  - master

install:
  - travis_retry npm install;

script:
  - travis_retry npm test;

after_success: 
  - travis_retry npm run coverage